[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "durep"
dynamic = ["version"]
description = "Create interactive HTML reports of disk usage from ncdu JSON files"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "SSI-DK" },
]
dependencies = ["ijson"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "pyright"]
all = ["pytest", "pytest-cov"]

[project.scripts]
durep = "durep.cli:main"

[project.urls]
Homepage = "git@github.com:ssi-dk/durep.git"
Repository = "git@github.com:ssi-dk/durep.git"

[tool.hatch.version]
path = "src/durep/__init__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/durep"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 100
