[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"

[project]
name = "durep"
dynamic = ["version"]
description = "Create interactive HTML reports of disk usage from ncdu JSON files"
license = "MIT"
requires-python = ">=3.11"
authors = [
    { name = "SSI-DK" },
]
dependencies = ["ijson"]

[project.optional-dependencies]
test = ["pytest", "pytest-cov", "hatchling", "hatch-vcs"]
dev = ["pytest", "pytest-cov", "pyright", "ruff", "hatchling", "hatch-vcs"]

[project.scripts]
durep = "durep.cli:main"

[project.urls]
Homepage = "git@github.com:ssi-dk/durep.git"
Repository = "git@github.com:ssi-dk/durep.git"

[tool.hatch.version]
source = "vcs"

[tool.hatch.build.hooks.custom]

[tool.hatch.build.targets.wheel]
packages = ["src/durep"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[tool.ruff]
line-length = 100
